[package]
name = "DMG-2025"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "2.6.0"
eframe = "0.30.0"
egui = "0.30.0"
env_logger = "0.11.6"
json = "0.12.4"
json5 = "0.4.1"
rodio = "0.20.1"
serde = {version = "1.0.217", features = ["derive"]}
serde-big-array = "0.5.1"
